name: Continuous integration testing

on:
  push:
    branches: [ dev ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code
      uses: actions/checkout@v2
      with:
        path: src/github.com/hashicorp/packer

    - name: Test
      working-directory: src/github.com/hashicorp/packer
      run: |
        sed -i 's/TestGetTerminalDimensions/_TestGetTerminalDimensions/' ./common/terminal_test.go
        make ci

    - name: Cross compile
      working-directory: src/github.com/hashicorp/packer
      run: |
        XC_OS="darwin linux windows" XC_ARCH="amd64" make bin

    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: darwin_amd64
        path: src/github.com/hashicorp/packer/pkg/darwin_amd64
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: linux_amd64
        path: src/github.com/hashicorp/packer/pkg/linux_amd64
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: windows_amd64
        path: src/github.com/hashicorp/packer/pkg/windows_amd64
