name: Go

on:
  push:
    branches:
    - master
    - 'chroot-*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code
      uses: actions/checkout@v2
      with:
        path: src/github.com/hashicorp/packer

    - name: Build
      run: |
        export GOPATH=`pwd`
        cd src/github.com/hashicorp/packer
        touch /dev/tty
        make ci
