name: Release

on:
  release:
    types: [ created ]

jobs:
  build:
    name: Create release assets
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code
      uses: actions/checkout@v2
      with:
        path: src/github.com/hashicorp/packer
      if: false
      
    - name: Build
      run: |
        echo ${{ github.event.release.upload_url }}
        export GOPATH=`pwd`
        #cd src/github.com/hashicorp/packer
        #touch /dev/tty
        #make ci
